In [ ]:
# Numpy :
NumPy (Numerical Python) is a powerful library for numerical computing, providing fast array operations, mathematical functions, and memory-efficient data structures.


In [ ]:
pip install numpy

In [ ]:
# ndarray !!
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
#  Special Arrays

print(np.zeros((3,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
print(np.ones((3,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
print(np.full((3,3),5))

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [ ]:
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
print(np.random.rand(3,3))

[[0.80985117 0.11106406 0.02132888]
 [0.42307098 0.8466203  0.25216376]
 [0.98719345 0.7800255  0.10670283]]


In [ ]:
print(np.arange(0,10,3))

[0 3 6 9]


In [ ]:
print(np.linspace(0,10,5))

[ 0.   2.5  5.   7.5 10. ]


In [ ]:
# Array Properties
arr.shape

(5,)

In [ ]:
arr.size

5

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
# indexing
print(arr[0])

print(arr[2:4])

print(arr[::2])

1
[3 4]
[1 3 5]


In [ ]:
# Reshaping & Transposing

arr = np.arange(1, 10)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [ ]:
print(arr.reshape(3,3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
arr.T

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Aggregation Functions
arr = np.array([1, 2, 3, 4, 5])
print(arr.min())
print(arr.max())
print(arr.sum())
print(arr.mean())
print(arr.std())
print(arr.var())


1
5
15
3.0
1.4142135623730951
2.0
